(ns epub-app.desktop
  (:require ["package:flutter/material.dart" :as m]
            [cljd.flutter :as f]
            [epub-app.state.store :as store]
            [epub-app.theme :as t]
            [epub-app.widgets.library :as library]
            [epub-app.widgets.reader :as reader]))

(defn app []
  (f/widget
   :watch [state store/app-state]
   (m/MaterialApp
    .title "MGL EPUB"
    .debugShowCheckedModeBanner false
    .theme t/app-theme
    .home
    (if (:book state)
      (reader/screen)
      (library/screen)))))
